"""Tambah tabel users untuk login

Revision ID: 0a64af4fee69
Revises: 9b74e1b8364c
Create Date: 2025-05-20 11:12:15.545420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a64af4fee69'
down_revision = '9b74e1b8364c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
