"""update table films

Revision ID: bbb55eb202db
Revises: 9e6450f8ec93
Create Date: 2025-05-26 20:14:48.038456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb55eb202db'
down_revision = '9e6450f8ec93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
