"""Add sinopsis column to films

Revision ID: fed3017c0ed8
Revises: 8d3b8bb563aa
Create Date: 2025-05-21 16:59:14.075217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed3017c0ed8'
down_revision = '8d3b8bb563aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('sinopsis', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'sinopsis')
    # ### end Alembic commands ###
