"""update statuses dan relationship

Revision ID: d91bcfc13951
Revises: f489d0b8126e
Create Date: 2025-05-26 17:47:40.886647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91bcfc13951'
down_revision = 'f489d0b8126e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_films_status_id_statuses', 'films', type_='foreignkey')
    op.drop_column('films', 'status_id')
    op.drop_constraint('fk_reviews_user_id', 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_user_id_users'), 'reviews', 'users', ['user_id'], ['id'])
    op.add_column('statuses', sa.Column('status', sa.String(), nullable=False))
    op.add_column('statuses', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('statuses', sa.Column('film_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('user_film_unique', 'statuses', ['user_id', 'film_id'])
    op.create_foreign_key(op.f('fk_statuses_user_id_users'), 'statuses', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_statuses_film_id_films'), 'statuses', 'films', ['film_id'], ['id'])
    op.drop_column('statuses', 'nama')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('nama', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_statuses_film_id_films'), 'statuses', type_='foreignkey')
    op.drop_constraint(op.f('fk_statuses_user_id_users'), 'statuses', type_='foreignkey')
    op.drop_constraint('user_film_unique', 'statuses', type_='unique')
    op.drop_column('statuses', 'film_id')
    op.drop_column('statuses', 'user_id')
    op.drop_column('statuses', 'status')
    op.drop_constraint(op.f('fk_reviews_user_id_users'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_user_id', 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('films', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_films_status_id_statuses', 'films', 'statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###
