"""update table film

Revision ID: 9e6450f8ec93
Revises: 7e5cb7a76e15
Create Date: 2025-05-26 19:59:32.234858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6450f8ec93'
down_revision = '7e5cb7a76e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('imdb_id', sa.String(), nullable=True))
    op.drop_constraint('uq_films_mdb_id', 'films', type_='unique')
    op.create_unique_constraint(op.f('uq_films_imdb_id'), 'films', ['imdb_id'])
    op.drop_column('films', 'mdb_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('mdb_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('uq_films_imdb_id'), 'films', type_='unique')
    op.create_unique_constraint('uq_films_mdb_id', 'films', ['mdb_id'])
    op.drop_column('films', 'imdb_id')
    # ### end Alembic commands ###
