"""Add imdb_id to films

Revision ID: 7e5cb7a76e15
Revises: d91bcfc13951
Create Date: 2025-05-26 19:54:09.950930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5cb7a76e15'
down_revision = 'd91bcfc13951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('mdb_id', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_films_mdb_id'), 'films', ['mdb_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_films_mdb_id'), 'films', type_='unique')
    op.drop_column('films', 'mdb_id')
    # ### end Alembic commands ###
