"""add user_id to reviews

Revision ID: f489d0b8126e
Revises: fed3017c0ed8
Create Date: 2025-05-25 17:20:32.669508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f489d0b8126e'
down_revision = 'fed3017c0ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_reviews_user_id',
        'reviews', 'users',
        ['user_id'], ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_reviews_user_id', 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###
