"""Add poster column to films

Revision ID: 8d3b8bb563aa
Revises: e02b9e40ef10
Create Date: 2025-05-21 16:34:41.791876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3b8bb563aa'
down_revision = 'e02b9e40ef10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('poster', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'poster')
    # ### end Alembic commands ###
